import type { Applicant } from "@/types";

export const mockData: Applicant[] = [
    {
        id: "1",
        name: "John Doe",
        location: "San Francisco, CA",
        position: "Software Engineer",
        resumeUrl: "https://www.example.com/resume",
        coverLetter: "I am a software engineer with 5 years of experience.",
        favorite: false,
        archived: false,
        notes: "Great candidate for the position.",
    },
    {
        id: "2",
        name: "Jane Doe",
        location: "New York, NY",
        position: "Product Manager",
        resumeUrl: "https://www.example.com/resume",
        coverLetter: "I am a product manager with 3 years of experience.",
        favorite: false,
        archived: false,
        notes: "Great candidate for the position.",
    },
    {
        id: "3",
        name: "Alice Smith",
        location: "Los Angeles, CA",
        position: "Data Scientist",
        resumeUrl: "https://www.example.com/resume",
        coverLetter: "I am a data scientist with 7 years of experience.",
        favorite: false,
        archived: false,
        notes: "Great candidate for the position.",
    },
    {
        id: "4",
        name: "Bob Johnson",
        location: "Chicago, IL",
        position: "UX Designer",
        resumeUrl: "https://www.example.com/resume",
        coverLetter: "I am a UX designer with 2 years of experience.",
        favorite: false,
        archived: false,
        notes: "Great candidate for the position.",
    },
    {
        id: "5",
        name: "Eve Brown",
        location: "Seattle, WA",
        position: "Software Engineer",
        resumeUrl: "https://www.example.com/resume",
        coverLetter: "I am a software engineer with 3 years of experience.",
        favorite: false,
        archived: false,
        notes: "Great candidate for the position.",
    },
    {
        id: "6",
        name: "Charlie Green",
        location: "Austin, TX",
        position: "Product Manager",
        resumeUrl: "https://www.example.com/resume",
        coverLetter: "I am a product manager with 5 years of experience.",
        favorite: false,
        archived: false,
        notes: "Great candidate for the position.",
    },
]