import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "SCORE", uid: "score", sortable: true},
  {name: "NAME", uid: "name", sortable: true},
  {name: "AGE", uid: "age", sortable: true},
  {name: "ROLE", uid: "role"},
  {name: "TEAM", uid: "team"},
  {name: "LOCATION", uid: "location"},
  {name: "EMAIL", uid: "email"},
  {name: "STATUS", uid: "status", sortable: true},
  {name: "STARS", uid: "stars", sortable: true},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "New", uid: "newApply"},
  {name: "Screening", uid: "screening"},
  {name: "Assessment", uid: "assessment"},
  {name: "Interview", uid: "interview"},
  {name: "Consideration", uid: "consideration"},
  {name: "Offer", uid: "offer"},
  {name: "Onboarding", uid: "onboarding"},
  {name: "Hired", uid: "hired"},
];

const applicants = [
  {
    id: 1,
    score: 98,
    name: "Tony Reichert",
    role: "Sr. Dev",
    team: "Development",
    status: "onboarding",
    age: "29",
    email: "tony.reichert@example.com",
    location: "New York City, US",
    stars: 5,
  },
  {
    id: 2,
    score: 97,
    name: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "offer",
    age: "25",
    email: "zoey.lang@example.com",
    location: "San Francisco, US",
    stars: 5,
  },
  {
    id: 3,
    score: 95,
    name: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    status: "consideration",
    age: "22",
    email: "jane.fisher@example.com",
    location: "Toronto, CA",
    stars: 5,
  },
  {
    id: 4,
    score: 93,
    name: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "newApply",
    age: "28",
    email: "william.howard@example.com",
    location: "London, UK",
    stars: 0,
  },
  {
    id: 5,
    score: 89,
    name: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "interview",
    age: "24",
    email: "kristen.cooper@example.com",
    location: "New York City, US",
    stars: 4,
  },
  {
    id: 6,
    score: 87,
    name: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    age: "29",
    email: "brian.kim@example.com",
    status: "newApply",
    location: "Melbourne, AU",
    stars: 0,
  },
  {
    id: 7,
    score: 84,
    name: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "assessment",
    age: "27",
    email: "michael.hunt@example.com",
    location: "Paris, FR",
    stars: 4,
  },
  {
    id: 8,
    score: 79,
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "screening",
    age: "31",
    email: "samantha.brooks@example.com",
    location: "Berlin, DE",
    stars: 4,
  },
  {
    id: 9,
    score: 75,
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "newApply",
    age: "33",
    email: "frank.harrison@example.com",
    location: "New York City, US",
    stars: 0,
  },
  {
    id: 10,
    score: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "newApply",
    age: "35",
    email: "emma.adams@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 11,
    score: 10,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "newApply",
    age: "22",
    email: "brandon.stevens@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 12,
    score: 10,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "newApply",
    age: "28",
    email: "megan.richards@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 13,
    score: 10,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "newApply",
    age: "37",
    email: "oliver.scott@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 14,
    score: 10,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "newApply",
    age: "30",
    email: "grace.allen@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 15,
    score: 10,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "newApply",
    age: "31",
    email: "noah.carter@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 16,
    score: 10,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "newApply",
    age: "29",
    email: "ava.perez@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 17,
    score: 10,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "newApply",
    age: "28",
    email: "liam.johnson@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 18,
    score: 10,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "newApply",
    age: "27",
    email: "sophia.taylor@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 19,
    score: 10,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "newApply",
    age: "32",
    email: "lucas.harris@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 20,
    score: 10,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "newApply",
    age: "26",
    email: "mia.robinson@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 21,
    score: 10,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "newApply",
    age: "22",
    email: "brandon.stevens@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 22,
    score: 10,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "newApply",
    age: "28",
    email: "megan.richards@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 23,
    score: 10,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "newApply",
    age: "37",
    email: "oliver.scott@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 24,
    score: 10,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "newApply",
    age: "30",
    email: "grace.allen@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 25,
    score: 10,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "newApply",
    age: "31",
    email: "noah.carter@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 26,
    score: 10,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "newApply",
    age: "29",
    email: "ava.perez@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 27,
    score: 10,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "newApply",
    age: "28",
    email: "liam.johnson@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 28,
    score: 10,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "newApply",
    age: "27",
    email: "sophia.taylor@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 29,
    score: 10,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "newApply",
    age: "32",
    email: "lucas.harris@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 30,
    score: 10,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "newApply",
    age: "26",
    email: "mia.robinson@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 31,
    score: 10,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "newApply",
    age: "22",
    email: "brandon.stevens@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 32,
    score: 10,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "newApply",
    age: "28",
    email: "megan.richards@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 33,
    score: 10,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "newApply",
    age: "37",
    email: "oliver.scott@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 34,
    score: 10,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "newApply",
    age: "30",
    email: "grace.allen@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 35,
    score: 10,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "newApply",
    age: "31",
    email: "noah.carter@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 36,
    score: 10,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "newApply",
    age: "29",
    email: "ava.perez@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 37,
    score: 10,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "newApply",
    age: "28",
    email: "liam.johnson@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 38,
    score: 10,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "newApply",
    age: "27",
    email: "sophia.taylor@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 39,
    score: 10,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "newApply",
    age: "32",
    email: "lucas.harris@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 40,
    score: 10,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "newApply",
    age: "26",
    email: "mia.robinson@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 41,
    score: 10,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "newApply",
    age: "22",
    email: "brandon.stevens@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 42,
    score: 10,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "newApply",
    age: "28",
    email: "megan.richards@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 43,
    score: 10,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "newApply",
    age: "37",
    email: "oliver.scott@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 44,
    score: 10,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "newApply",
    age: "30",
    email: "grace.allen@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 45,
    score: 10,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "newApply",
    age: "31",
    email: "noah.carter@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 46,
    score: 10,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "newApply",
    age: "29",
    email: "ava.perez@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 47,
    score: 10,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "newApply",
    age: "28",
    email: "liam.johnson@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 48,
    score: 10,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "newApply",
    age: "27",
    email: "sophia.taylor@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 49,
    score: 10,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "newApply",
    age: "32",
    email: "lucas.harris@example.com",
    location: "New York, US",
    stars: 0,
  },
  {
    id: 50,
    score: 10,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "newApply",
    age: "26",
    email: "mia.robinson@example.com",
    location: "New York, US",
    stars: 0,
  },
];

export {columns, applicants, statusOptions};
